#服务器端口
server:
  port: 9000

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catering?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: fuck3148481
